# Generated by Django 4.2.4 on 2023-11-29 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usertype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertypename', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'usertype',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('firstname', models.CharField(max_length=50, unique=True)),
                ('lastname', models.CharField(max_length=50, unique=True)),
                ('phonenumber', models.IntegerField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('usertypeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.usertype')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
